name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    # check out the repository
    - uses: actions/checkout@v4

    - name: compile giza (Mac OS)
      if: runner.os == 'macOS'
      run: |
           ./configure --prefix=/opt/homebrew
           make install

    - name: compile giza (Linux)
      if: runner.os == 'Linux'
      run: |
           ./configure
           make install
