name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:

    # make sure we have gfortran installed and linked
    - name: Install gfortran compiler
      uses: fortran-lang/setup-fortran@v1
      with:
        compiler: gcc

    # check out the repository
    - uses: actions/checkout@v4

    - name: compile and install giza
      run: |
        ./configure
        make
        sudo make install

    # Set up Xvfb for graphical tests
    - name: Set up and start Xvfb
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        Xvfb :99 -screen 0 1920x1080x24 &
        export DISPLAY=:99

    # Run tests
    - name: Run test programs, pressing enter to all prompts
      if: matrix.os == 'ubuntu-latest'
      run: |
        yes "" | make check
 
    # Run tests
    - name: show the test logs
      if: matrix.os == 'ubuntu-latest'
      run: |
        cat test/C/test-suite.log