name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    # check out the repository
    - uses: actions/checkout@v4

    - name: compile giza (Mac OS)
      if: runner.os == 'macOS'
      run: |
           echo "PKG_CONFIG_PATH=$PKG_CONFIG_PATH"
           pkg-config --version
           echo "Checking cairo:"
           pkg-config --cflags cairo
           pkg-config --libs cairo
           echo "Checking paths:"
           pkg-config --variable=includedir cairo
           pkg-config --variable=libdir cairo
           ./configure --prefix=/opt/homebrew
           make install

    - name: compile giza (Linux)
      if: runner.os == 'Linux'
      run: |
           ./configure
           make
           sudo make install
