name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    #- name: Install dependencies (macOS)
     # if: runner.os == 'macOS'
     # run: |
     #   brew install cairo
     #   brew install pkg-config
     #   brew install libx11
     #   brew install freetype
     #   brew install fontconfig

    #- name: Install dependencies (Ubuntu)
    #  if: runner.os == 'Linux'
      #run: |
      #  sudo apt-get update
      #  sudo apt-get install -y libcairo2-dev
      #  sudo apt-get install -y libx11-dev
      #  sudo apt-get install -y pkg-config
      #  sudo apt-get install -y libfreetype6-dev
      #  sudo apt-get install -y libfontconfig1-dev

    - name: Install gfortran compiler
      uses: fortran-lang/setup-fortran@v1
      with:
         compiler: gcc

    - name: Check gfortran version
      run: gfortran --version

    # check out the repository
    - uses: actions/checkout@v3

    - name: compile giza
      run: |
           ./configure
           make
